### ISSUE TITLE
No numbers sectors yet?

### ISSUE THREAD

**Issue by ZaharitIngot** [Twcash/Aquarion#40]
**Describe the bug**

**To Reproduce**
1. Land on 'any number sector'
2. See error

**Expected behavior**
Expected i can capture and play it.

**Screenshots**
![image](https://github.com/Twcash/Aquarion/assets/141028724/2a6afa40-c3e3-4c59-9bec-448d79e92b5b)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
:((((

**Comment by Twcash** [comment]
There is no optional sectors. That will be in 2.3.0
