### ISSUE TITLE
Byte (unit) issue

### ISSUE THREAD

**Issue by ZaharitIngot** [Twcash/Aquarion#41]
**Describe the bug**

**To Reproduce**
1. Go to 'Correlative reconstructor'
2. See Zoarchid makes 2 different units

**Expected behavior**
A clear and concise description of what you expected to happen(SUPER CLEAR)

**Screenshots**
![image](https://github.com/Twcash/Aquarion/assets/141028724/29915d7d-970f-4262-8537-da9de38b6ee0)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
COID DOESNT MAKE BYTE!!!

**Comment by Twcash** [comment]
This is/was an ongoing issue not worth a bug patch at the moment. Currently me and other people are working on porting content and fixing bugs. We appreciate you and feel free to bring any more up
